version: '2'
services:
  mildred:
    build:
      context: .
      dockerfile: Dockerfile
    image: mildred
    container_name: mildred
    ports:
      - 8017:8017
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../:/mildred
    command: python main.wsgi 8017
